<footer class="white-text">
        <div class="fabout">
            About Us:
            <ul class="aboutlist">
                <li><a href="aboutme1.html">Azmain Taraqqi</a></li>
                <li><a href="aboutme2.html">Wei Hang Lee</a></li>
                <li><a href="aboutme3.html">Dhirrennraj Vijayaraj</a></li>
                <li><a href="aboutme4.html">Chan Chun Hui</a></li>
            </ul>
        </div>
        <div class="fcontact">
            Contact Us:
            <ul class="contactlist">
                <li>
                    <a href="mailto:105804016@students.swinburne.edu.my">105804016@students.swinburne.edu.my</a>
                </li>
                <li>
                    <a href="mailto:102788735@students.swinburne.edu.my">102788735@students.swinburne.edu.my</a>
                </li>
                <li>
                    <a href="mailto:102761273@students.swinburne.edu.my">102761273@students.swinburne.edu.my</a>
                </li>
                <li>
                    <a href="mailto:101235900@students.swinburne.edu.my">101235900@students.swinburne.edu.my</a>
                </li>
            </ul>
        </div>
    </footer>
</body>
</html>