<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="styles/style.css" rel="stylesheet">
    <title>Home - Root Flower</title>
</head>
<body>
    <header class="white-text">
        <div class="top">
            <img class="logo" src="styles/images/logo.jpg">
            <div id="title"><a href=index.html>root flower</a></div>
        </div>
        <nav>
            <ul class="nav-menu">
                <li class="dropdown">
                    Products
                    <ul class="dropdown-content">
                        <li><a href="product1.html">Hand Bouquets</a></li>
                        <li><a href="product2.html">CNY Decorations</a></li>
                        <li><a href="product3.html">Grand Openings</a></li>
                        <li><a href="product4.html">Graduation</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    Activities
                    <ul class="dropdown-content">
                        <li><a href="workshops.php">Workshops</a></li>
                        <li><a href="promo.html">Promotions</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    Registration
                    <ul class="dropdown-content">
                        <li><a href="workshop_form.php">Workshop Registration</a></li>
                        <li><a href="membership_form.php">Membership Registration</a></li>
                    </ul>
                </li>
                <li>
                    <a href="enquiry_form.php">Enquiry Form</a> 
                </li>
            </ul>
            <div id="login">
                <a href="login_form.php">Login</a>
            </div>
        </nav>
    </header>